// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hmhoefzxkyyivgctpuyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtaG9lZnp4a3l5aXZnY3RwdXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzY0MjUsImV4cCI6MjA3MzgxMjQyNX0.wu0VaXduEqvT_kobx6uKzaXWHdbZUb7TLmv7lzLwQCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);